# Generated by Django 3.0.5 on 2022-05-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_auto_20220506_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
